version: "3.9"
services:
  ull:
    build: 
      context: ./ull
      dockerfile: Dockerfile
    networks:
      - aries
    ports:
      - "3104:3104"
      - "8080:8080"
  whip:
    build: 
      context: ./whip
      dockerfile: Dockerfile
    networks:
      - aries
    depends_on:
      - "ull"
    ports:
      - "1234:1234"
      - "8000:8000"
networks:
  aries:
